### ISSUE TITLE
Add information about required release?

### ISSUE THREAD

**Issue by larshp** [sautermi0/ABAPTestIsolationDemo#5]
https://blogs.sap.com/2022/01/21/test-doubles-are-coming-to-function-modules/ says function modules are from 7.56

I dont know about the other frameworks

**Comment by sautermi0** [comment]
Good point, I'll add it as soon as I'll figure it out... I found the release versions of everything except the authority check and the RAP things...

**Comment by sautermi0** [comment]
Will fix it in the linked pull request #6
