### ISSUE TITLE
Repository is hard to understand without installing it first

### ISSUE THREAD

**Issue by ConjuringCoffee** [sautermi0/ABAPTestIsolationDemo#7]
Right now, the README lists the test classes to structure the documentation. This makes it hard to understand the repository without installing it first. 

How about separating each example into a package and then referring to the package in the documentation?

**Comment by ConjuringCoffee** [comment]
This issue is part of my review for the repository's inclusion in the Clean ABAP style guide: https://github.com/SAP/styleguides/pull/337

**Comment by ConjuringCoffee** [comment]
On closer look, it seems like all examples are mixed within `zati_cl_code_under_test`. I feel like this makes it unnecessarily confusing 😅

**Comment by sautermi0** [comment]
The idea was to show one class with various different kinds of dependencies and then one test class in zati_cl_code_under_test to show how to isolate from that kind of dependency...

But yeah, splitting it into separate packages would probably be better, I'll do that 👍

**Comment by sautermi0** [comment]
Will be handled in the new (official) SAP-Samples-Repository as this will be the future place for the code.
